teleop:
  publish_rate_hz: 20

  topics:
    cmd_vel: /cmd_vel   

  speed:
    linear:
      value: 0.5
      min: 0.1
      max: 1.0
      step: 0.1
    angular:
      value: 0.5
      min: 0.1
      max: 1.0
      step: 0.1

  keys:
    move:
      forward: w
      backward: s
      left: a
      right: d
      stop: x       

    speed:
      linear_down: '1'
      linear_up: '2'
      angular_down: '3'
      angular_up: '4'

  deadman_timeout_ms: 300
